create table ORDERS
(
   ORDER_ID             INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
   VEHICLE_ID           INT NOT NULL,
   USER_ID              INT NOT NULL,
   LICENCE_ID           INT NOT NULL,
   PICK_UP_DATE         DATETIME NOT NULL,
   DROP_OFF_DATE        DATETIME NOT NULL,
   RENT_COST            DECIMAL(10,2) NOT NULL,
   PROCESSED            BIT NOT NULL,
   REJECTED             BIT NOT NULL,
   REJECT_DESC          VARCHAR(100),
   PICKED               BIT NOT NULL,
   RETURNED             BIT NOT NULL,
   DAMAGED              BIT NOT NULL,
   DAMAGE_DESC          VARCHAR(100),
   DAMAGE_COST          DECIMAL(10,2),
   PAID                 BIT NOT NULL,
  
)



CREATE TABLE LICENCE
(
   LICENCE_ID         INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   LAST_NAME            VARCHAR(50) NOT NULL,
   FIRST_NAME           VARCHAR(50) NOT NULL,
   PATRONYMIC           VARCHAR(50),
   PHONE_NO             VARCHAR(50) NOT NULL,  
   BIRTHDAY             DATETIME NOT NULL,
   L_SERIES             CHAR(10) NOT NULL,
   L_NUMBER             CHAR(10) NOT NULL,
   WHO_ISSUED           VARCHAR(50) NOT NULL,
   ADDRESS              VARCHAR(50) NOT NULL,
   WHEN_ISSUED          DATETIME NOT NULL,

)


CREATE TABLE USERS
(
   USER_ID              INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   USERTYPE_ID          INT NOT NULL,
   LOGIN                VARCHAR(50) NOT NULL,
   PASSWORD             VARCHAR(50) NOT NULL,
   
)


CREATE TABLE USERTYPES
(
   USERTYPE_ID          INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   USERTYPE             VARCHAR(50) NOT NULL,

)


CREATE TABLE VEHICLES
(
   VEHICLE_ID           INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   MAKE                 VARCHAR(50) NOT NULL,
   MODEL                VARCHAR(50) NOT NULL,
   AUTO_GEARBOX         BIT NOT NULL,
   AIR_CONDITIONER      BIT NOT NULL,
   SEATS                INT NOT NULL,
   DAILY_PRICE          DECIMAL(10,2) NOT NULL,

)

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_LICENCE FOREIGN KEY (LICENCE_ID)
      REFERENCES LICENCE (LICENCE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID)
      REFERENCES USERS (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_VEHICLE FOREIGN KEY (VEHICLE_ID)
      REFERENCES VEHICLES (VEHICLE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USERS ADD CONSTRAINT FK_USERTYPE_USER FOREIGN KEY (USERTYPE_ID)
      REFERENCES USERTYPES (USERTYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
